server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
  servlet:
    context-path: /testing
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  profiles:
    active:
      #       - prod
      - dev
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      file-size-threshold: 20MB
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true

mybatis:
  mapper-locations:
    - classpath*:mappers/**/*.xml
  configuration:
    use-column-label: false
  configuration-properties:
    schema: uwjx
#pagehelper:
#  auto-dialect: true
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
